### ISSUE TITLE
I can't find demo.py

### ISSUE THREAD

**Issue by btniu** [yinkalario/General-Purpose-Sound-Recognition-Demo#5]
Thank you for your share. There is a sentence that "python demo.py MODEL_PATH='Cnn9_GMP_64x64_300000_iterations_mAP=0.37.pth?download=1'" in README.md. But I can't find demo.py. Can you please help me sir?

**Comment by andres-fr** [comment]
Hi, thanks a lot for raising this issue. Indeed that was a slip up in the documentation from my part.

Can you try to replace `python demo.py` with `python -m sed_demo`? This works on my end.

The reason is that we moved the functionality from `demo.py` into [`__main__.py`](https://github.com/yinkalario/General-Purpose-Sound-Recognition-Demo/blob/master/sed_demo/__main__.py). The `__main__` file of a package can always be invoked using `-m <PACKAGE_NAME>`, this is a Python convention.

> I've also just pushed the README changes to master, updating the execution script as per above, so future users don't run into this.

Hope this helps, let me know otherwise. And apologies again!
Cheers,  
Andres

---

For future reference, this is a test command that works on my end (MODEL_PATH may have to be adapted):

```
python -m sed_demo MODEL_PATH='models/Cnn9_GMP_64x64_300000_iterations_mAP=0.37.pth' TOP_K=10
```

**Comment by btniu** [comment]
Thank you for your help!
